"use client"

import { useState, useEffect, useCallback } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import type { ModelImage } from "@/types/session"

interface ResultsScreenProps {
  prompt: string
  sessionId: string
  modelImages: ModelImage[]
  imagePaths: string[]
  onReset: () => void
}

export function ResultsScreen({ prompt, sessionId, modelImages, imagePaths, onReset }: ResultsScreenProps) {
  const [selected, setSelected] = useState<number | null>(null)
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const [lightbox, setLightbox] = useState<number | null>(null)
  const [downloading, setDownloading] = useState(false)

  const closeLightbox = useCallback(() => setLightbox(null), [])

  useEffect(() => {
    if (lightbox === null) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeLightbox()
    }
    window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [lightbox, closeLightbox])

  const handleDownload = async (idx: number) => {
    setDownloading(true)
    try {
      const src = `/api/session-image?path=${encodeURIComponent(modelImages[idx].imagePath)}`
      const res = await fetch(src)
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${modelImages[idx].modelSlug}.png`
      a.click()
      URL.revokeObjectURL(url)
    } finally {
      setDownloading(false)
    }
  }

  const handleSave = async () => {
    if (selected === null) return
    setSaving(true)
    await fetch('/api/sessions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId,
        timestamp: new Date().toISOString(),
        prompt,
        generatedImagePaths: imagePaths,
        modelImages,
        preferredModel: modelImages[selected].modelSlug,
      }),
    }).catch(() => {})
    setSaving(false)
    setSaved(true)
  }

  return (
    <div className="min-h-screen" style={{ background: "#F0FDFA" }}>
      <div className="max-w-4xl mx-auto px-6 pt-10 pb-32">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="flex flex-col gap-6"
        >
          <div>
            <h1 className="text-2xl font-bold text-[#134E4A] mb-1">Results</h1>
            <p className="text-sm text-[#5F8A87] mb-2">
              {modelImages.length} model{modelImages.length !== 1 ? 's' : ''} generated an image. Tap the one you like best.
            </p>
            <div className="bg-white/60 rounded-xl px-4 py-2 inline-block">
              <p className="text-[#134E4A] text-sm italic">&ldquo;{prompt}&rdquo;</p>
            </div>
          </div>

          {/* Image grid */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {modelImages.map((mi, idx) => {
              const src = `/api/session-image?path=${encodeURIComponent(mi.imagePath)}`
              const isSelected = selected === idx
              return (
                <button
                  key={mi.modelSlug}
                  type="button"
                  onClick={() => { setSelected(idx); setSaved(false) }}
                  className={`relative rounded-2xl overflow-hidden transition-all active:scale-[0.97] ${
                    isSelected
                      ? "ring-3 ring-[#0D9488] ring-offset-2 ring-offset-[#F0FDFA]"
                      : "ring-1 ring-[#99F6E4]"
                  }`}
                >
                  <div className="relative aspect-[3/4] w-full">
                    <Image
                      src={src}
                      alt={`Generated by ${mi.modelLabel}`}
                      fill
                      className="object-cover"
                    />
                  </div>
                  <div className={`absolute bottom-0 left-0 right-0 px-3 py-2 text-xs font-bold text-center ${
                    isSelected
                      ? "bg-[#0D9488] text-white"
                      : "bg-black/50 text-white/90"
                  }`}>
                    {mi.modelLabel}
                  </div>
                  {isSelected && (
                    <div className="absolute top-2 right-2 w-7 h-7 rounded-full bg-[#0D9488] flex items-center justify-center shadow-lg">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path d="M2.5 7L5.5 10L11.5 4" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </div>
                  )}
                  {/* Expand button */}
                  <button
                    type="button"
                    tabIndex={0}
                    aria-label={`View ${mi.modelLabel} full size`}
                    onClick={(e) => { e.stopPropagation(); setLightbox(idx) }}
                    className="absolute top-2 left-2 w-7 h-7 rounded-full bg-black/50 hover:bg-black/70 flex items-center justify-center transition-colors"
                  >
                    <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                      <path d="M1 5V1H5M8 1H12V5M12 8V12H8M5 12H1V8" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </button>
                </button>
              )
            })}
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-2">
            {!saved ? (
              <Button
                onClick={handleSave}
                disabled={selected === null || saving}
                className="flex-1"
                size="lg"
              >
                {saving ? "Saving..." : selected !== null ? `Save — ${modelImages[selected].modelLabel}` : "Pick a favourite"}
              </Button>
            ) : (
              <div className="flex-1 flex flex-col items-center gap-2">
                <p className="text-[#0D9488] font-semibold text-sm">Saved! You picked {modelImages[selected!].modelLabel}.</p>
              </div>
            )}
          </div>

          <button
            onClick={onReset}
            className="text-[#5F8A87] text-sm underline underline-offset-2 text-center"
          >
            Generate again with a new prompt
          </button>
        </motion.div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {lightbox !== null && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/85 p-4"
            onClick={closeLightbox}
          >
            <motion.div
              initial={{ scale: 0.92, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.92, opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="relative max-w-2xl w-full flex flex-col items-center gap-4"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Close */}
              <button
                type="button"
                aria-label="Close"
                onClick={closeLightbox}
                className="self-end w-9 h-9 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
              >
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path d="M1 1L13 13M13 1L1 13" stroke="white" strokeWidth="2" strokeLinecap="round"/>
                </svg>
              </button>

              {/* Image */}
              <div className="relative w-full aspect-[3/4] rounded-2xl overflow-hidden shadow-2xl">
                <Image
                  src={`/api/session-image?path=${encodeURIComponent(modelImages[lightbox].imagePath)}`}
                  alt={`Generated by ${modelImages[lightbox].modelLabel}`}
                  fill
                  className="object-contain"
                  sizes="(max-width: 768px) 100vw, 672px"
                />
              </div>

              {/* Label + Download */}
              <div className="flex items-center justify-between w-full px-1">
                <span className="text-white/80 text-sm font-medium">{modelImages[lightbox].modelLabel}</span>
                <button
                  type="button"
                  onClick={() => handleDownload(lightbox)}
                  disabled={downloading}
                  className="flex items-center gap-2 bg-white/10 hover:bg-white/20 disabled:opacity-50 text-white text-sm font-medium px-4 py-2 rounded-full transition-colors"
                >
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path d="M7 1v8M4 6l3 3 3-3M1 11h12" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {downloading ? "Saving…" : "Save image"}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
