/** One image generated by a specific model */
export interface ModelImage {
  modelSlug: string
  modelLabel: string
  imagePath: string
}

export interface SessionRecord {
  sessionId: string
  timestamp: string
  prompt: string
  generatedImagePaths: string[]
  modelImages: ModelImage[]
  preferredModel: string | null
}
